"""Cross-team module resolution and the SPEC v2 constant fallback for the sim2sim package.

The whole point of the MuJoCo harness is *parity*: it must be driven by the same numbers and the
same preprocessing code as the Isaac Lab environment. Therefore nothing in ``duckiebot_rl.sim2sim``
is allowed to hardcode a robot dimension. Every value is pulled through
:func:`resolve_robot_params`, which prefers the authoritative module owned by the ``[assets]``
engineer and only falls back to a literal transcription of SPEC v2 S2/S3.2 when that module does
not exist yet.

Resolution order (first hit wins), and what each provides:

===============================  ==========================================================
Shared module                    Provides
===============================  ==========================================================
``duckiebot_rl.assets.params``   robot dimensions / masses / actuator numbers (S2, S3.2)
``duckiebot_rl.dr.preprocess``   S4.3 observation operator chain (torch)
``duckiebot_rl.preprocess``      same, alternative location named by SPEC v2 S6.1
``duckiebot_rl.wrappers.delay``  S5.3 step-2 actuation delay ring / S4.3 step-9 obs delay
``duckiebot_rl.camera_math``     ``quat_cam_ros`` and the MuJoCo ``xyaxes`` derivation (S2)
``duckiebot_rl.city``            map loader, tile textures and lane graph (S3.3)
===============================  ==========================================================

When a module is missing the resolver raises :class:`SharedModuleUnavailable` with the exact import
path that has to land, or emits :class:`SpecFallbackWarning` and continues with the SPEC v2 literal
values when a safe local equivalent exists. ``PARAMS_SOURCE`` records which happened, so a report
generated by :mod:`duckiebot_rl.sim2sim.evaluate` always states its provenance.
"""

from __future__ import annotations

import dataclasses
import importlib
import math
import sys
import warnings
from collections.abc import Iterable
from dataclasses import dataclass
from types import ModuleType
from typing import Any

__all__ = [
    "CityParams",
    "DRRanges",
    "ObsParams",
    "RobotParams",
    "SharedModuleUnavailable",
    "SimParams",
    "SpecFallbackWarning",
    "environment_report",
    "format_environment_report",
    "mj_camera_xyaxes",
    "quat_cam_ros",
    "resolve_camera_math",
    "resolve_city",
    "resolve_city_params",
    "resolve_delay",
    "resolve_dr_ranges",
    "resolve_preprocess",
    "resolve_robot_params",
    "resolve_sim_params",
]


class SpecFallbackWarning(UserWarning):
    """Warning issued when a shared module is absent and SPEC v2 literals are used instead."""


class SharedModuleUnavailable(ImportError):
    """A shared module that has no safe local substitute is missing from the interpreter."""


#: Modules that exist but raised while importing, as ``name -> repr(exception)``. A shared module
#: that is *absent* and one that is *broken* are different problems with different owners, and the
#: harness used to report both as "not importable"; this records the difference so the fallback
#: warning can name the real cause.
IMPORT_FAILURES: dict[str, str] = {}


def _try_import(name: str) -> ModuleType | None:
    """Import ``name`` and return the module, or None when it cannot be imported.

    A module that is simply absent returns None quietly, which is the expected state while another
    team's module has not landed yet. A module that EXISTS but raises (a syntax error, or a missing
    third-party dependency such as torch in the tools venv) is a different failure: it is recorded
    in :data:`IMPORT_FAILURES` and reported through a :class:`SpecFallbackWarning` naming the
    exception, so it cannot masquerade as "not landed yet" and silently downgrade the harness to
    the SPEC literals.

    Args:
        name: the dotted module path.

    Returns:
        The imported module, or None.
    """
    try:
        return importlib.import_module(name)
    except ModuleNotFoundError as exc:
        absent = exc.name is None or name == exc.name or name.startswith(f"{exc.name}.")
        if absent:
            return None
        detail = f"{type(exc).__name__}: {exc}"
        IMPORT_FAILURES[name] = detail
        warnings.warn(
            f"{name} exists but failed to import ({detail}). sim2sim is treating it as absent and "
            f"will fall back to the SPEC v2 literals. This is a broken dependency, not a module "
            f"that has yet to land.",
            SpecFallbackWarning,
            stacklevel=2,
        )
        return None
    except Exception as exc:
        detail = f"{type(exc).__name__}: {exc}"
        IMPORT_FAILURES[name] = detail
        warnings.warn(
            f"{name} exists but raised while importing ({detail}). sim2sim is treating it as "
            f"absent and will fall back to the SPEC v2 literals. Fix the module: the fallback is "
            f"not a substitute for the shared numbers.",
            SpecFallbackWarning,
            stacklevel=2,
        )
        return None


# --------------------------------------------------------------------------------------- params
@dataclass(frozen=True)
class RobotParams:
    """Duckiebot dimensional and actuator constants (SPEC v2 S2 and S3.2).

    All lengths are metres, masses kilograms, inertias kg.m^2, torques N.m, angular rates rad/s.
    Frames follow REP-103 (x forward, y left, z up) with ``base_link`` at the wheel-axle midpoint,
    which sits ``wheel_radius`` above the ground when the robot is level.
    """

    wheel_radius: float = 0.0318
    wheel_separation: float = 0.100
    wheel_width: float = 0.027
    base_mass: float = 1.000
    wheel_mass: float = 0.050
    base_com: tuple[float, float, float] = (-0.015, 0.0, 0.015)
    base_inertia_diag: tuple[float, float, float] = (1.877e-3, 3.169e-3, 4.108e-3)
    wheel_inertia_diag: tuple[float, float, float] = (1.568e-5, 2.528e-5, 1.568e-5)
    chassis_size: tuple[float, float, float] = (0.18, 0.13, 0.075)
    chassis_center: tuple[float, float, float] = (-0.015, 0.0, 0.0267)
    caster_radius: float = 0.0165
    caster_center: tuple[float, float, float] = (-0.085, 0.0, -0.0153)
    camera_block_size: tuple[float, float, float] = (0.03, 0.03, 0.03)
    marker_radius: float = 0.025
    marker_center: tuple[float, float, float] = (-0.03, 0.0, 0.09)
    effort_limit: float = 0.15
    velocity_limit: float = 35.0
    joint_damping: float = 0.05
    joint_armature: float = 2.0e-4
    joint_friction: float = 0.010
    passive_joint_damping: float = 0.0
    motor_k: float = 27.0
    wheel_friction: float = 1.0
    caster_friction: float = 0.0
    robot_width: float = 0.131
    encoder_ticks_per_rev: int = 135
    v_max: float = 0.6
    omega_max: float = 4.0
    camera_pos: tuple[float, float, float] = (0.078, 0.0, 0.0692)
    camera_pitch_down_deg: float = 25.3
    camera_focal_px: float = 65.98
    camera_fovy_deg: float = 88.26
    clipping_range: tuple[float, float] = (0.05, 6.0)
    brake_dw_max: float = 12.0
    pwm_release_duty: float = 0.01
    actuation_delay_s: float = 0.150
    base_link_name: str = "base_link"
    left_wheel_link_name: str = "left_wheel_link"
    right_wheel_link_name: str = "right_wheel_link"
    left_wheel_joint_name: str = "left_wheel_joint"
    right_wheel_joint_name: str = "right_wheel_joint"

    @property
    def base_height(self) -> float:
        """Height of ``base_link`` above the ground plane when level (equals the wheel radius)."""
        return self.wheel_radius

    @property
    def ground_clearance(self) -> float:
        """Gap between the bottom face of the chassis collision box and the ground."""
        return self.base_height + self.chassis_center[2] - 0.5 * self.chassis_size[2]

    def validate(self) -> None:
        """Assert the geometric invariants SPEC v2 S2 pins down.

        Raises:
            ValueError: if the caster is not tangent to the ground, if the chassis clearance is not
                the specified 21 mm, or if a mass or limit is non-positive.
        """
        caster_contact = self.base_height + self.caster_center[2] - self.caster_radius
        if abs(caster_contact) > 1e-9:
            raise ValueError(
                f"caster is not tangent to the ground: contact z = {caster_contact:.6f} m; "
                f"S2 requires the caster centre exactly one radius above the ground"
            )
        if abs(self.ground_clearance - 0.021) > 1e-6:
            raise ValueError(
                f"chassis ground clearance {self.ground_clearance:.6f} m != 0.021 m (S2 item 24)"
            )
        positive = (
            "base_mass",
            "wheel_mass",
            "wheel_radius",
            "wheel_separation",
            "effort_limit",
            "velocity_limit",
            "joint_armature",
        )
        for name in positive:
            if getattr(self, name) <= 0.0:
                raise ValueError(f"{name} must be positive, got {getattr(self, name)!r}")
        if self.joint_friction < 0.0 or self.joint_damping < 0.0:
            raise ValueError("joint friction and damping must be non-negative")


@dataclass(frozen=True)
class SimParams:
    """Integrator and rate settings (SPEC v2 S5.2 and S8.1).

    ``physics_dt`` and ``decimation`` are deliberately identical to the Isaac Lab side: critic item
    J flagged the v1 mismatch (Isaac 1/120 x 8 versus MuJoCo 1/240 x 16) as a confound hiding inside
    the headline C1-vs-C5 delta. :class:`duckiebot_rl.sim2sim.env.MjEnvCfg` re-exposes them so the
    confound can be re-introduced deliberately as an ablation, never by accident.
    """

    physics_dt: float = 1.0 / 240.0
    decimation: int = 16
    integrator: str = "implicitfast"
    cone: str = "elliptic"
    impratio: float = 10.0
    solver: str = "Newton"
    iterations: int = 5
    ls_iterations: int = 20
    gravity: tuple[float, float, float] = (0.0, 0.0, -9.81)
    solref_wheel: tuple[float, float] = (0.004, 1.0)
    solref_default: tuple[float, float] = (0.005, 1.0)
    solimp_wheel: tuple[float, float, float] = (0.97, 0.995, 0.001)
    solimp_default: tuple[float, float, float] = (0.95, 0.99, 0.001)

    @property
    def control_dt(self) -> float:
        """Seconds per control step."""
        return self.physics_dt * self.decimation

    @property
    def control_hz(self) -> float:
        """Control frequency in Hz (15.0 for the SPEC v2 defaults)."""
        return 1.0 / self.control_dt

    def validate(self) -> None:
        """Assert the S8.3 item-3 rate requirements.

        Raises:
            ValueError: if the decimation is not a positive integer, or the integrator is an
                explicit one. SPEC v2 S8.1 locks ``implicitfast`` for a *structural* reason: PhysX
                integrates its implicit velocity drive implicitly, and matching structure is the
                job of this package. The v1 justification (a measured -87% forward speed under
                ``Euler``) does not reproduce at the SPEC v2 armature, and
                ``tests/unit/test_mj_kinematics.py`` carries that measurement; the lock stays
                because the stability margin is under a factor of three and system identification
                is free to move both the armature and the servo gain.
        """
        if self.decimation < 1 or int(self.decimation) != self.decimation:
            raise ValueError(f"decimation must be a positive integer, got {self.decimation!r}")
        if self.physics_dt <= 0.0:
            raise ValueError("physics_dt must be positive")
        if self.integrator not in ("implicitfast", "implicit", "RK4"):
            raise ValueError(
                f"integrator {self.integrator!r} is not allowed; SPEC v2 S8.1 locks 'implicitfast' "
                f"because MuJoCo integrates the <velocity kv> gain explicitly under Euler"
            )


@dataclass(frozen=True)
class ObsParams:
    """Observation chain constants (SPEC v2 S4.3)."""

    render_w: int = 192
    render_h: int = 128
    obs_w: int = 96
    obs_h: int = 48
    crop_top: int = 16
    box: int = 2
    frame_stack: int = 3
    stack_stride: int = 2
    ring_depth: int = 5
    vec_dim: int = 8
    vec_priv_dim: int = 14

    @property
    def obs_channels(self) -> int:
        """Channel count of the stacked RGB observation (9 for 3 stacked RGB frames)."""
        return 3 * self.frame_stack


@dataclass(frozen=True)
class DRRanges:
    """Dynamics domain-randomization clamps (SPEC v2 S7.3).

    Only the axes the MuJoCo harness can realize are listed. Visual axes V14-V19 are layer-1
    photometric randomization applied inside the shared preprocess chain, so condition C6 gets them
    for free without any MuJoCo-side code. Axes that live in the Isaac scene graph (V1-V8, V13)
    have no MuJoCo counterpart and are documented as a known coverage gap of C6.

    Field names deliberately match the ``dr_*`` attributes of the shared params object so the
    adapter is an identity map.
    """

    dr_wheel_radius_scale: tuple[float, float] = (0.95, 1.05)
    dr_wheel_radius_asymmetry: tuple[float, float] = (-0.06, 0.06)
    dr_baseline_m: tuple[float, float] = (0.090, 0.110)
    dr_tire_friction_static: tuple[float, float] = (0.40, 1.40)
    dr_tire_friction_dynamic_scale: tuple[float, float] = (0.7, 1.0)
    dr_base_mass_kg: tuple[float, float] = (0.85, 1.40)
    dr_base_inertia_zz_scale: tuple[float, float] = (0.7, 1.4)
    dr_com_xy_m: tuple[float, float] = (-0.020, 0.020)
    dr_com_z_m: tuple[float, float] = (-0.010, 0.010)
    dr_motor_gain: tuple[float, float] = (0.60, 1.40)
    dr_motor_trim: tuple[float, float] = (-0.12, 0.12)
    dr_battery_sag: tuple[float, float] = (0.90, 1.04)
    dr_deadband_duty: tuple[float, float] = (0.0, 0.15)
    dr_delay_control_steps: tuple[int, int] = (1, 3)
    dr_delay_substep: tuple[float, float] = (0.0, 0.9)
    dr_motor_lag_alpha: tuple[float, float] = (0.4, 0.9)
    dr_obs_latency_steps: tuple[int, int] = (0, 2)
    dr_effort_limit_nm: tuple[float, float] = (0.06, 0.25)
    dr_brake_authority_beta: tuple[float, float] = (0.4, 1.0)
    dr_armature_scale: tuple[float, float] = (0.5, 2.0)
    dr_joint_friction_nm: tuple[float, float] = (0.005, 0.03)
    dr_wheel_slip_frac: tuple[float, float] = (0.0, 0.10)
    dr_encoder_dropout: tuple[float, float] = (0.0, 0.02)


_DR_ADAPTER = {f.name: (f.name,) for f in dataclasses.fields(DRRanges)}


def resolve_dr_ranges() -> tuple[DRRanges, str]:
    """Return the S7.3 dynamics DR clamps, preferring the shared params module.

    Fields the shared module does not carry keep their SPEC v2 defaults; unlike
    :func:`resolve_robot_params` this is safe, because a DR clamp is a training-time range rather
    than a physical constant that both simulators must agree on.

    Returns:
        ``(ranges, provenance)``.
    """
    target = DRRanges()
    for mod_name in _PARAM_MODULES:
        module = _try_import(mod_name)
        if module is None:
            continue
        source: Any = None
        for attr in _PARAM_ATTRS:
            source = getattr(module, attr, None)
            if source is not None:
                break
        adapted, missing = _adapt(source if source is not None else module, target, _DR_ADAPTER)
        if len(missing) == len(_DR_ADAPTER):
            continue
        resolved = len(_DR_ADAPTER) - len(missing)
        if not missing:
            return adapted, f"{mod_name} (all {resolved} axes)"
        # A partial match is a silent mixture of authoritative and local numbers, which is exactly
        # what resolve_robot_params raises to prevent. Here it cannot raise, because the harness
        # must still run while [assets] lands the last axes, so the provenance string NAMES them.
        # Anything reading provenance() therefore sees which axes are still local.
        return adapted, (
            f"{mod_name} ({resolved}/{len(_DR_ADAPTER)} axes; SPEC v2 S7.3 fallback for "
            f"{', '.join(sorted(missing))})"
        )
    return target, f"SPEC v2 S7.3 fallback (all {len(_DR_ADAPTER)} axes)"


@dataclass(frozen=True)
class CityParams:
    """Track dimensional facts (SPEC v2 S3.3). Overridden per map by the map YAML ``tile_size``.

    ``duckiebot_rl.city.spec`` is the source of truth for every field in the first group; they are
    resolved through :func:`resolve_city_params` and the literals here are only the fallback for an
    interpreter that cannot import the shared city package. They are transcribed from
    :data:`duckiebot_rl.city.spec.NOMINAL_TILE_SPEC`, and :meth:`validate` refuses any set that
    disagrees with the painted geometry, so the fallback cannot silently drift.

    The second group (walls and the visual tile thickness) has no ``[city]`` counterpart: Isaac's
    city has no walls and its tile quads are authored, not extruded. Those stay MuJoCo-local, the
    same way :class:`SimParams` keeps the cone and solver settings local.

    .. warning::
       ``lane_offset_tiles`` is 0.20 tile, not the 0.22 of duckietown-world
       (:data:`duckiebot_rl.city.spec.DUCKIETOWN_WORLD_LANE_OFFSET_TILE`). 0.20 tile is the
       geometric centre of the *painted* clear lane, which is the line the policy can actually see.
       The two differ by 11.7 mm at the nominal pitch, 11% of a half lane, and that difference
       would appear as a constant bias in the headline S8.4 ``lane_rms_m`` and ``lane_max_m``
       metrics. SPEC v2 S3.3 quotes both figures; the architect's binding decision is that
       ``duckiebot_rl.city.spec`` wins, and :meth:`validate` enforces it numerically.

    Attributes:
        tile_pitch: tile repeat distance in metres.
        lane_offset_tiles: lane centreline offset from the tile centreline, in tile units.
        lane_width: clear drivable lane width in metres (``w_ep`` of the S5.4 reward).
        white_tape_w: width of the solid white lane-edge tape in metres.
        yellow_tape_w: width of the dashed yellow centre tape in metres.
        wall_height: perimeter wall height in metres (MuJoCo-local, visual only).
        wall_thickness: perimeter wall thickness in metres (MuJoCo-local, visual only).
        tile_visual_thickness: thickness of the visual tile slab in metres (MuJoCo-local).
    """

    tile_pitch: float = 0.585
    lane_offset_tiles: float = 0.20
    lane_width: float = 0.210
    white_tape_w: float = 0.048
    yellow_tape_w: float = 0.024
    wall_height: float = 0.30
    wall_thickness: float = 0.02
    tile_visual_thickness: float = 0.001

    @property
    def lane_offset_m(self) -> float:
        """Lane centreline offset from the tile centreline, in metres."""
        return self.lane_offset_tiles * self.tile_pitch

    @property
    def painted_lane_center_m(self) -> float:
        """Centre of the painted clear lane, in metres from the tile centreline.

        This is the line a vision policy sees: half the yellow tape plus half the clear lane.
        """
        return 0.5 * self.yellow_tape_w + 0.5 * self.lane_width

    @property
    def curve_radius_inner_m(self) -> float:
        """Lane-centre radius of the inner (right-turn) arc of a curve tile, in metres."""
        return 0.5 * self.tile_pitch - self.lane_offset_m

    @property
    def curve_radius_outer_m(self) -> float:
        """Lane-centre radius of the outer (left-turn) arc of a curve tile, in metres."""
        return 0.5 * self.tile_pitch + self.lane_offset_m

    def rescaled(self, tile_pitch: float) -> CityParams:
        """Return these dimensions scaled so the tile pitch becomes ``tile_pitch``.

        A map may declare its own ``tile_size``. A texture painted at one pitch and mapped onto a
        quad of another keeps every marking at the same *fraction* of the tile, so the lane width
        and the tape widths scale with the pitch while ``lane_offset_tiles``, being dimensionless,
        does not. This mirrors ``duckiebot_rl.city.spec.TileSpec.rescaled``.

        Args:
            tile_pitch: the target tile pitch in metres.

        Returns:
            The rescaled, validated :class:`CityParams`.

        Raises:
            ValueError: if ``tile_pitch`` is not positive, or the result fails :meth:`validate`.
        """
        if tile_pitch <= 0.0:
            raise ValueError(f"tile_pitch must be positive, got {tile_pitch!r}")
        k = tile_pitch / self.tile_pitch
        out = dataclasses.replace(
            self,
            tile_pitch=tile_pitch,
            lane_width=self.lane_width * k,
            white_tape_w=self.white_tape_w * k,
            yellow_tape_w=self.yellow_tape_w * k,
        )
        out.validate()
        return out

    def validate(self, tol_m: float = 1e-6) -> None:
        """Assert the lane graph is placed on the line the texture paints.

        Args:
            tol_m: allowed disagreement between the lane centreline and the painted lane centre.

        Raises:
            ValueError: if a dimension is non-positive, if the markings do not fit inside the tile,
                or if the lane centreline is not the centre of the painted clear lane. The last one
                is the S8.4 metric bias described in the class docstring: the policy would be scored
                against a line it cannot see.
        """
        positive = {
            "tile_pitch": self.tile_pitch,
            "lane_width": self.lane_width,
            "white_tape_w": self.white_tape_w,
            "yellow_tape_w": self.yellow_tape_w,
            "wall_height": self.wall_height,
            "wall_thickness": self.wall_thickness,
            "tile_visual_thickness": self.tile_visual_thickness,
            "lane_offset_tiles": self.lane_offset_tiles,
        }
        for name, value in positive.items():
            if value <= 0.0:
                raise ValueError(f"CityParams.{name} must be positive, got {value!r}")
        outer = 0.5 * self.yellow_tape_w + self.lane_width + self.white_tape_w
        if outer >= 0.5 * self.tile_pitch:
            raise ValueError(
                f"markings do not fit: the white tape outer edge sits at {outer * 1e3:.1f} mm but "
                f"the tile half-pitch is {0.5 * self.tile_pitch * 1e3:.1f} mm"
            )
        delta = self.lane_offset_m - self.painted_lane_center_m
        if abs(delta) > tol_m:
            raise ValueError(
                f"lane centreline is {self.lane_offset_m * 1e3:.2f} mm from the tile centreline "
                f"but the painted clear lane is centred at {self.painted_lane_center_m * 1e3:.2f} "
                f"mm, a {delta * 1e3:+.2f} mm disagreement. The policy would be scored against a "
                f"line it cannot see, biasing lane_rms_m and lane_max_m by that amount. "
                f"duckiebot_rl.city.spec is the source of truth for all three numbers; a "
                f"lane_center_offset_mm override there (the duckietown-world 0.22 tile, say) is "
                f"not usable by this harness."
            )


CITY_SOURCE: str = "unresolved"

_CITY_MODULES = ("duckiebot_rl.city.spec", "duckiebot_lab.city.spec")
_CITY_SPEC_ATTRS = ("NOMINAL_TILE_SPEC", "TILE_SPEC", "SPEC")

# Explicit adapter from the [city]-owned TileSpec onto the sim2sim view, as
# ``target field -> ((source attribute, unit scale), ...)``, first hit wins. TileSpec speaks
# millimetres for its raw fields and metres for its derived properties, so the scale is part of the
# mapping. Exactly like _PARAM_ADAPTER, an unmapped field is a hard error rather than a silent
# fallback: a mixture of authoritative and literal track dimensions is the drift this module exists
# to prevent.
_CITY_ADAPTER: dict[str, tuple[tuple[str, float], ...]] = {
    "tile_pitch": (("pitch_m", 1.0), ("tile_pitch_mm", 1e-3)),
    "lane_offset_tiles": (("lane_center_offset_tile", 1.0),),
    "lane_width": (("lane_width_m", 1.0), ("clear_lane_mm", 1e-3)),
    "white_tape_w": (("white_tape_mm", 1e-3),),
    "yellow_tape_w": (("yellow_tape_mm", 1e-3),),
}


def resolve_city_params(
    tile_spec: Any = None, base: CityParams | None = None, strict: bool = False
) -> tuple[CityParams, str]:
    """Return the authoritative :class:`CityParams` and a human-readable provenance string.

    ``duckiebot_rl.city.spec.TileSpec`` is the single source of truth for the tile pitch, the lane
    offset, the lane width and the tape widths. This is the city-side counterpart of
    :func:`resolve_robot_params` and behaves the same way: every mapped field must be present, and
    a partial match raises instead of silently mixing authoritative and fallback numbers.

    Args:
        tile_spec: a ``TileSpec`` to adapt; None resolves ``NOMINAL_TILE_SPEC`` from the shared
            city package. Pass one explicitly to build a scene from a randomized (S7.2 axis V9) or
            rescaled tile geometry.
        base: supplies the MuJoCo-only fields (walls, visual tile thickness); defaults to the
            SPEC v2 set.
        strict: raise instead of falling back to the SPEC v2 literals when the city package is
            absent.

    Returns:
        ``(params, provenance)`` where ``provenance`` names where the numbers came from.

    Raises:
        SharedModuleUnavailable: if ``strict`` and no shared city spec module can be imported.
        ValueError: if a shared city spec exists but does not expose every adapter field, or if the
            resulting geometry fails :meth:`CityParams.validate`.
    """
    global CITY_SOURCE
    target = base if base is not None else CityParams()
    source: Any = tile_spec
    provenance_module = (
        f"{type(tile_spec).__module__}.{type(tile_spec).__name__} (caller-supplied)"
        if tile_spec is not None
        else "caller-supplied TileSpec"
    )
    if source is None:
        for mod_name in _CITY_MODULES:
            module = _try_import(mod_name)
            if module is None:
                continue
            for attr in _CITY_SPEC_ATTRS:
                candidate = getattr(module, attr, None)
                if candidate is not None:
                    source, provenance_module = candidate, f"{mod_name}.{attr}"
                    break
            if source is not None:
                break
    if source is None:
        if strict:
            raise SharedModuleUnavailable(
                "no shared city geometry module found; the [city] engineer must land one of "
                + " or ".join(_CITY_MODULES)
            )
        warnings.warn(
            "duckiebot_rl.city.spec is not importable; sim2sim is using the SPEC v2 S3.3 literal "
            "fallback for the track geometry. Those literals are a transcription of "
            "NOMINAL_TILE_SPEC and CityParams.validate() rejects any set that disagrees with the "
            "painted lane, but the shared module is what keeps them honest.",
            SpecFallbackWarning,
            stacklevel=2,
        )
        target.validate()
        CITY_SOURCE = "SPEC v2 S3.3 fallback (duckiebot_rl.sim2sim._resolve)"
        return target, CITY_SOURCE

    values: dict[str, float] = {}
    missing: list[str] = []
    for name, candidates in _CITY_ADAPTER.items():
        for attr, scale in candidates:
            raw = getattr(source, attr, None)
            if raw is None:
                continue
            values[name] = float(raw) * scale
            break
        else:
            missing.append(name)
    if missing:
        raise ValueError(
            f"{provenance_module} was imported but does not expose {missing}. sim2sim refuses to "
            f"mix authoritative and fallback track dimensions. Extend _CITY_ADAPTER in "
            f"duckiebot_rl/sim2sim/_resolve.py (requires [city] + [sim2sim] agreement)."
        )
    params = dataclasses.replace(target, **values)
    params.validate()
    CITY_SOURCE = provenance_module
    return params, CITY_SOURCE


_FALLBACK_ROBOT = RobotParams()
PARAMS_SOURCE: str = "unresolved"

_PARAM_MODULES = ("duckiebot_rl.assets.params", "duckiebot_lab.assets.params")
_PARAM_ATTRS = ("DUCKIEBOT", "ROBOT", "ROBOT_PARAMS", "PARAMS")

# Explicit adapter from the [assets]-owned DuckiebotParams attribute names to the sim2sim view.
# It is deliberately exhaustive and deliberately NOT name-guessing: a partial name match would
# silently mix authoritative numbers with fallback literals, which is the exact drift this module
# exists to prevent. Every entry lists the candidate attribute or property names, first hit wins.
_PARAM_ADAPTER: dict[str, tuple[str, ...]] = {
    "wheel_radius": ("wheel_radius_m", "wheel_radius"),
    "wheel_separation": ("wheel_baseline_m", "wheel_separation", "wheel_baseline"),
    "wheel_width": ("wheel_width_m", "wheel_width"),
    "base_mass": ("base_mass_kg", "base_mass"),
    "wheel_mass": ("wheel_mass_kg", "wheel_mass"),
    "base_com": ("base_com_base_frame_m", "base_com"),
    "base_inertia_diag": ("base_inertia_about_com", "base_inertia_diag"),
    "wheel_inertia_diag": ("wheel_inertia_about_com", "wheel_inertia_diag"),
    "chassis_size": ("chassis_size_m", "chassis_size"),
    "chassis_center": ("chassis_center_base_frame_m", "chassis_center"),
    "caster_radius": ("caster_radius_m", "caster_radius"),
    "caster_center": ("caster_center_base_frame_m", "caster_center"),
    "camera_block_size": ("camera_block_size_m", "camera_block_size"),
    "marker_radius": ("duckie_marker_radius_m", "marker_radius"),
    "marker_center": ("duckie_marker_center_base_frame_m", "marker_center"),
    "effort_limit": ("wheel_effort_limit_nm", "effort_limit"),
    "velocity_limit": ("wheel_velocity_limit_rad_s", "velocity_limit"),
    "joint_damping": ("joint_damping",),
    "joint_armature": ("joint_armature_kg_m2", "joint_armature"),
    "joint_friction": ("joint_friction_nm", "joint_friction"),
    "motor_k": ("motor_constant_k_rad_s_per_duty", "motor_k"),
    "wheel_friction": ("wheel_friction_static", "wheel_friction"),
    "caster_friction": ("caster_friction",),
    "robot_width": ("robot_width_m", "robot_width"),
    "encoder_ticks_per_rev": ("encoder_ticks_per_rev",),
    "v_max": ("v_cmd_max_m_s", "v_max"),
    "omega_max": ("omega_cmd_max_rad_s", "omega_max"),
    "camera_pos": ("camera_pos_base_frame_m", "camera_pos"),
    "camera_pitch_down_deg": ("camera_pitch_down_deg",),
    "camera_focal_px": ("camera_focal_px",),
    "camera_fovy_deg": ("camera_vfov_deg", "camera_fovy_deg"),
    "clipping_range": ("camera_clipping_range_m", "clipping_range"),
    "brake_dw_max": ("brake_dw_max_rad_s_per_step", "brake_dw_max"),
    "pwm_release_duty": ("pwm_release_duty",),
    "actuation_delay_s": ("actuation_delay_s",),
    "base_link_name": ("base_link_name",),
    "left_wheel_link_name": ("left_wheel_link_name",),
    "right_wheel_link_name": ("right_wheel_link_name",),
    "left_wheel_joint_name": ("left_wheel_joint_name",),
    "right_wheel_joint_name": ("right_wheel_joint_name",),
}

# Only these two live on the shared params object; the rest of SimParams is MuJoCo-specific.
_SIM_ADAPTER: dict[str, tuple[str, ...]] = {
    "physics_dt": ("sim_dt_s", "physics_dt"),
    "decimation": ("decimation",),
}


def _coerce(field: dataclasses.Field, value: Any) -> Any:
    """Coerce a value pulled from a foreign module into the declared dataclass field type."""
    if isinstance(value, (list, tuple)):
        return tuple(float(v) for v in value)
    if field.type in ("str", str):
        return str(value)
    if field.type in ("int", int):
        return int(value)
    return float(value)


def _adapt(source: Any, target: Any, adapter: dict[str, tuple[str, ...]]) -> tuple[Any, list[str]]:
    """Rebuild ``target`` from ``source`` using ``adapter``; return it plus the unresolved fields.

    Args:
        source: the foreign parameter object (or a mapping).
        target: the sim2sim dataclass instance holding the fallback defaults.
        adapter: mapping of target field name to candidate source attribute names.

    Returns:
        ``(new_target, missing)`` where ``missing`` lists target fields that had no source value.
    """
    if isinstance(source, dict):

        def getter(key: str) -> Any:
            return source.get(key)
    else:

        def getter(key: str) -> Any:
            return getattr(source, key, None)

    by_name = {f.name: f for f in dataclasses.fields(target)}
    values: dict[str, Any] = {}
    missing: list[str] = []
    for target_field, candidates in adapter.items():
        for key in candidates:
            raw = getter(key)
            if raw is None:
                continue
            values[target_field] = _coerce(by_name[target_field], raw)
            break
        else:
            missing.append(target_field)
    return dataclasses.replace(target, **values), missing


def resolve_robot_params(strict: bool = False) -> tuple[RobotParams, str]:
    """Return the authoritative :class:`RobotParams` and a human-readable provenance string.

    Args:
        strict: if True, raise instead of falling back to the SPEC v2 literals.

    Returns:
        ``(params, provenance)`` where ``provenance`` names the module the numbers came from.

    Raises:
        SharedModuleUnavailable: if ``strict`` and no shared params module can be imported.
        ValueError: if a shared params module exists but does not expose the whole adapter, which
            would leave the MJCF a silent mixture of authoritative and fallback numbers.
    """
    global PARAMS_SOURCE
    for mod_name in _PARAM_MODULES:
        module = _try_import(mod_name)
        if module is None:
            continue
        source: Any = None
        for attr in _PARAM_ATTRS:
            source = getattr(module, attr, None)
            if source is not None:
                break
        if source is None:
            source = module
        params, missing = _adapt(source, _FALLBACK_ROBOT, _PARAM_ADAPTER)
        if missing:
            raise ValueError(
                f"{mod_name} was imported but does not expose {missing}. sim2sim refuses to mix "
                f"authoritative and fallback robot numbers. Extend _PARAM_ADAPTER in "
                f"duckiebot_rl/sim2sim/_resolve.py (requires [assets] + [sim2sim] agreement)."
            )
        params.validate()
        PARAMS_SOURCE = f"{mod_name}.{type(source).__name__}"
        return params, PARAMS_SOURCE
    if strict:
        raise SharedModuleUnavailable(
            "no shared robot-parameter module found; the [assets] engineer must land one of "
            + " or ".join(_PARAM_MODULES)
        )
    warnings.warn(
        "duckiebot_rl.assets.params is not importable; sim2sim is using the SPEC v2 S2/S3.2 "
        "literal fallback. Delete duckiebot_rl.sim2sim._resolve._FALLBACK_ROBOT once [assets] "
        "lands the real module, so Isaac and MuJoCo cannot drift apart.",
        SpecFallbackWarning,
        stacklevel=2,
    )
    _FALLBACK_ROBOT.validate()
    PARAMS_SOURCE = "SPEC v2 S2/S3.2 fallback (duckiebot_rl.sim2sim._resolve)"
    return _FALLBACK_ROBOT, PARAMS_SOURCE


def resolve_sim_params(base: SimParams | None = None) -> tuple[SimParams, str]:
    """Return :class:`SimParams` with the rate fields taken from the shared params module.

    Only ``physics_dt`` and ``decimation`` are shared: the integrator, cone and solver settings are
    MuJoCo-specific and have no Isaac counterpart. Taking the rates from the same object as the
    Isaac env is what removes critic item J's integration-rate confound.

    Args:
        base: a :class:`SimParams` supplying the MuJoCo-only fields; defaults to the SPEC v2 set.

    Returns:
        ``(sim_params, provenance)``.
    """
    target = base if base is not None else SimParams()
    for mod_name in _PARAM_MODULES:
        module = _try_import(mod_name)
        if module is None:
            continue
        source: Any = None
        for attr in _PARAM_ATTRS:
            source = getattr(module, attr, None)
            if source is not None:
                break
        adapted, missing = _adapt(source if source is not None else module, target, _SIM_ADAPTER)
        if not missing:
            adapted.validate()
            return adapted, f"{mod_name} (rates)"
    target.validate()
    return target, "SPEC v2 S5.2/S8.1 fallback"


def _resolve_any(names: Iterable[str], what: str, required_attrs: Iterable[str] = ()) -> ModuleType:
    """Import the first module in ``names`` exposing every attribute in ``required_attrs``."""
    tried = list(names)
    for name in tried:
        module = _try_import(name)
        if module is None:
            continue
        if all(hasattr(module, attr) for attr in required_attrs):
            return module
    raise SharedModuleUnavailable(
        f"{what} is unavailable. sim2sim requires one of {tried} exposing "
        f"{list(required_attrs)}. That module is owned by another engineer; it must land before "
        f"the MuJoCo vision path can claim parity with Isaac."
    )


def resolve_preprocess() -> ModuleType:
    """Return the shared S4.3 preprocessing module (torch).

    Returns:
        The imported preprocessing module.

    Raises:
        SharedModuleUnavailable: if neither candidate module exists.
    """
    return _resolve_any(
        ("duckiebot_rl.dr.preprocess", "duckiebot_rl.preprocess"),
        "the shared observation preprocessing chain (SPEC v2 S4.3)",
    )


def resolve_delay() -> ModuleType | None:
    """Return the shared delay-ring module, or None if the local numpy twin should be used."""
    return _try_import("duckiebot_rl.wrappers.delay")


def resolve_camera_math() -> ModuleType | None:
    """Return the shared camera-math module if it exists, else None."""
    return _try_import("duckiebot_rl.camera_math")


def resolve_city() -> ModuleType | None:
    """Return the shared city package if it exists, else None."""
    return _try_import("duckiebot_rl.city")


# ---------------------------------------------------------------------------------- camera math
def quat_cam_ros(pitch_down_rad: float) -> tuple[float, float, float, float]:
    """Return the ``(w, x, y, z)`` quaternion of the ROS optical frame expressed in ``base_link``.

    The ROS camera convention is +Z forward, +X right, +Y down. ``pitch_down_rad`` is a positive
    scalar meaning "nose down"; no other code in the sim2sim package touches a camera sign.

    Golden values pinned by SPEC v2 S2: pitch 0 gives ``(0.5, -0.5, 0.5, -0.5)`` and pitch
    25.3 deg gives ``(0.37837, -0.59736, 0.59736, -0.37837)``.

    Args:
        pitch_down_rad: downward camera pitch in radians.

    Returns:
        The unit quaternion as ``(w, x, y, z)``.

    Raises:
        ValueError: if a shared ``camera_math`` module returns something that is not a quaternion,
            or if the pitch is outside the representable open range (-90 deg, +90 deg).
    """
    shared = resolve_camera_math()
    if shared is not None and hasattr(shared, "quat_cam_ros"):
        q = tuple(float(v) for v in shared.quat_cam_ros(pitch_down_rad))
        if len(q) != 4:
            raise ValueError(f"camera_math.quat_cam_ros returned {len(q)} components, expected 4")
        return q  # type: ignore[return-value]
    if not -math.pi / 2.0 < pitch_down_rad < math.pi / 2.0:
        raise ValueError(f"pitch_down_rad {pitch_down_rad!r} is outside (-pi/2, +pi/2)")
    # The target rotation has columns [right, down, forward] with right = (0, -1, 0),
    # down = (-sin p, 0, -cos p) and forward = (cos p, 0, -sin p). Its trace is -sin p, so the
    # standard trace formula collapses to the closed form below (checked against both S2 goldens).
    sin_p = math.sin(pitch_down_rad)
    lo = math.sqrt(1.0 - sin_p) / 2.0
    hi = math.sqrt(1.0 + sin_p) / 2.0
    return (lo, -hi, hi, -lo)


def _quat_columns(q: tuple[float, float, float, float]) -> tuple[tuple[float, ...], ...]:
    """Return the three columns of the rotation matrix of quaternion ``(w, x, y, z)``."""
    w, x, y, z = q
    col0 = (1 - 2 * (y * y + z * z), 2 * (x * y + w * z), 2 * (x * z - w * y))
    col1 = (2 * (x * y - w * z), 1 - 2 * (x * x + z * z), 2 * (y * z + w * x))
    col2 = (2 * (x * z + w * y), 2 * (y * z - w * x), 1 - 2 * (x * x + y * y))
    return col0, col1, col2


def mj_camera_xyaxes(pitch_down_rad: float) -> tuple[float, ...]:
    """Return the MuJoCo ``xyaxes`` (6 numbers) for a camera pitched ``pitch_down_rad`` down.

    MuJoCo cameras look along -Z of their own frame with +Y up, so ``xyaxes`` is ``[right ; up]``
    expressed in the parent body frame. Both vectors are derived from :func:`quat_cam_ros` so that
    Isaac, MuJoCo and the deploy node cannot disagree: the ROS optical X axis *is* MuJoCo's camera
    X, and MuJoCo's camera Y is the negated ROS optical Y (down becomes up).

    Args:
        pitch_down_rad: downward camera pitch in radians.

    Returns:
        ``(rx, ry, rz, ux, uy, uz)``.
    """
    right, down, _forward = _quat_columns(quat_cam_ros(pitch_down_rad))
    up = tuple(-v for v in down)
    return tuple(right) + up


def mj_camera_forward(pitch_down_rad: float) -> tuple[float, ...]:
    """Return the camera viewing direction in the parent body frame (ROS optical +Z)."""
    _right, _down, forward = _quat_columns(quat_cam_ros(pitch_down_rad))
    return tuple(forward)


# ------------------------------------------------------------------------------ env diagnostics
_MUJOCO_VENV_INSTALL = (
    "d:/Personal/personal/mujoco_venv/Scripts/python.exe -m pip install torch "
    "--index-url https://download.pytorch.org/whl/cpu",
    "d:/Personal/personal/mujoco_venv/Scripts/python.exe -m pip install "
    "opencv-python-headless Pillow pyyaml onnxruntime usd-core",
)

_REQUIREMENTS = {
    "mujoco": "physics and offscreen rendering: mjcf, track, env, sysid, evaluate",
    "numpy": "arrays: everything",
    "torch": "shared S4.3 preprocess and the TorchScript policy: env (rgb obs), evaluate",
    "PIL": "city tile-texture generator: track in textured mode",
    "yaml": "MapFormat1 map files: track when loading a map from disk",
    "cv2": "robot-side rectification parity fixtures: optional",
}


def environment_report() -> dict[str, Any]:
    """Return a machine-readable description of what this interpreter can and cannot run.

    Returns:
        A dict with ``python``, ``packages`` (name -> version or None), ``requirements``,
        ``shared_modules`` (import path -> bool) and ``install_hints`` (exact pip commands).
    """
    packages: dict[str, str | None] = {}
    for name in _REQUIREMENTS:
        module = _try_import(name)
        packages[name] = getattr(module, "__version__", "unknown") if module else None
    shared = {
        "duckiebot_rl.assets.params": _try_import("duckiebot_rl.assets.params") is not None,
        "duckiebot_rl.dr.preprocess": _try_import("duckiebot_rl.dr.preprocess") is not None,
        "duckiebot_rl.preprocess": _try_import("duckiebot_rl.preprocess") is not None,
        "duckiebot_rl.wrappers.delay": _try_import("duckiebot_rl.wrappers.delay") is not None,
        "duckiebot_rl.camera_math": _try_import("duckiebot_rl.camera_math") is not None,
        "duckiebot_rl.city": _try_import("duckiebot_rl.city") is not None,
    }
    complete = bool(packages["torch"]) and bool(packages["PIL"]) and bool(packages["yaml"])
    return {
        "python": sys.executable,
        "python_version": sys.version.split()[0],
        "packages": packages,
        "requirements": dict(_REQUIREMENTS),
        "shared_modules": shared,
        "install_hints": [] if complete else list(_MUJOCO_VENV_INSTALL),
    }


def format_environment_report(report: dict[str, Any] | None = None) -> str:
    """Render :func:`environment_report` as a human-readable block of text.

    Args:
        report: a previously produced report, or None to generate a fresh one.

    Returns:
        The formatted multi-line string.
    """
    rep = report if report is not None else environment_report()
    lines = [f"interpreter : {rep['python']}  (python {rep['python_version']})", "packages:"]
    for name, version in rep["packages"].items():
        state = f"OK {version}" if version else "MISSING"
        lines.append(f"  {name:<8} {state:<18} needed for: {rep['requirements'][name]}")
    lines.append("shared modules owned by other engineers:")
    for name, present in rep["shared_modules"].items():
        lines.append(f"  {name:<32} {'present' if present else 'ABSENT (fallback in use)'}")
    if rep["install_hints"]:
        lines.append("to complete this interpreter (SPEC v2 M0):")
        lines.extend(f"  {cmd}" for cmd in rep["install_hints"])
    return "\n".join(lines)
