"""Clean-room procedural Duckietown city: dimensions, textures, maps, lane graph, USD.

Nothing in this package loads a Duckietown asset. Every texture is painted from the millimetre
dimensions in :mod:`.spec`, every layout is generated by :mod:`.maps`, and the USD stage is
authored as text ``.usda`` by :mod:`.usd_builder` (SPEC v2 S3.1 / S3.3 / S3.4).

Module map
----------
==================  =============================================  ==========================
module              purpose                                        third-party imports
==================  =============================================  ==========================
:mod:`.spec`        millimetre facts, palettes, DR buckets          numpy
:mod:`.tiles`       texture painting and a PNG codec                numpy
:mod:`.maps`        YAML format, validator, layouts, generator      numpy, PyYAML
:mod:`.lane_graph`  exact lanes, batched ``(d, psi, ds)`` query     numpy, PyYAML, torch
:mod:`.usd_builder` text ``.usda`` authoring, no Kit required       numpy, PyYAML, pxr
==================  =============================================  ==========================

Submodules are imported **lazily** (PEP 562) so that a venv with only numpy can still do
``from duckiebot_rl.city.tiles import render_tile`` without dragging in torch, PyYAML or USD.
Touching a name in the table above imports exactly the module that provides it.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - resolved by type checkers, never at run time
    from . import lane_graph, maps, spec, tiles, usd_builder  # noqa: F401
    from .lane_graph import BatchedLaneGraph, LaneGraph, LaneQuery, progress_delta  # noqa: F401
    from .maps import (  # noqa: F401  # noqa: F401
        BUILTIN_MAP_NAMES,
        CityMap,
        builtin_map,
        eval_maps,
        load_map,
        save_map,
        variant_maps,
    )
    from .spec import (  # noqa: F401  # noqa: F401  # noqa: F401
        IDEAL_PALETTE,
        NOMINAL_TILE_SPEC,
        PHOTO_PALETTE,
        ColorPalette,
        TileSpec,
        TileSpecRanges,
        geometry_buckets,
        palette_buckets,
    )
    from .tiles import (  # noqa: F401  # noqa: F401
        TILE_KINDS,
        TileStyle,
        read_png,
        render_tile,
        save_tile_set,
        write_png,
    )
    from .usd_builder import build_city_usda, build_ground_usda  # noqa: F401

#: Public name -> submodule that defines it.
_EXPORTS: dict[str, str] = {
    "ColorPalette": "spec",
    "IDEAL_PALETTE": "spec",
    "NOMINAL_TILE_SPEC": "spec",
    "PHOTO_PALETTE": "spec",
    "TileSpec": "spec",
    "TileSpecRanges": "spec",
    "geometry_buckets": "spec",
    "palette_buckets": "spec",
    "TILE_KINDS": "tiles",
    "TileStyle": "tiles",
    "read_png": "tiles",
    "render_tile": "tiles",
    "save_tile_set": "tiles",
    "write_png": "tiles",
    "BUILTIN_MAP_NAMES": "maps",
    "CityMap": "maps",
    "builtin_map": "maps",
    "eval_maps": "maps",
    "load_map": "maps",
    "save_map": "maps",
    "variant_maps": "maps",
    "BatchedLaneGraph": "lane_graph",
    "LaneGraph": "lane_graph",
    "LaneQuery": "lane_graph",
    "progress_delta": "lane_graph",
    "build_city_usda": "usd_builder",
    "build_ground_usda": "usd_builder",
}

_SUBMODULES = ("spec", "tiles", "maps", "lane_graph", "usd_builder")

__all__ = sorted({*_EXPORTS, *_SUBMODULES})


def __getattr__(name: str) -> Any:
    """Import submodules and their public names on first access (PEP 562).

    Args:
        name: Attribute being looked up on the package.

    Returns:
        The submodule or the exported object.

    Raises:
        AttributeError: If ``name`` is not part of the public API.
    """
    if name in _SUBMODULES:
        return importlib.import_module(f".{name}", __name__)
    if name in _EXPORTS:
        module = importlib.import_module(f".{_EXPORTS[name]}", __name__)
        return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    """Return the public API for tab completion."""
    return list(__all__)
